---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: check_before_start
          image: python-with-requests:alpine3.20
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - /tmp/check.py
          env:
            - name: readiness_url_1
              value: "https://github.com"
            - name: readiness_url_2
              value: "http://nginx:8080"
          volumeMounts:
            - mountPath: /tmp
              name: check_url
          _init: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 1m
              memory: 4Mi
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
          name: web
      volumes:
        - name: check_url
          configMap:
            defaultMode: 511
            name: check_url.py
